In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal, stats
import pandas as pd

import json

SMALL_SIZE = 18
MEDIUM_SIZE = 10
BIGGER_SIZE = 12

plt.rc('font', size=SMALL_SIZE)          # controls default text sizes
plt.rc('axes', titlesize=18)     # fontsize of the axes title
plt.rc('axes', labelsize=MEDIUM_SIZE)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=10)    # fontsize of the tick labels
plt.rc('ytick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('legend', fontsize=15)    # legend fontsize
plt.rc('figure', titlesize=35)  # fontsize of the figure title

plt.rcParams.update({
"text.usetex": True,
"font.family": "serif",
"text.latex.preamble": r"\usepackage{amsmath}"
})

# Nasa 1

In [40]:
with open("experiment_results/nasa1_100_2025-01-27-11-48-34.json", 'r') as f:
    data = json.load(f)

mse_gibbs_mean, mse_gibbs_std = np.mean(np.sqrt(np.stack(data[0])), axis=1), np.std(np.sqrt(np.stack(data[0])), axis=1)
mse_gibbs_lap_1_mean, mse_gibbs_lap_1_std = np.mean(np.sqrt(np.stack(data[1])), axis=1), np.std(np.sqrt(np.stack(data[1])), axis=1)
mse_gibbs_lap_2_mean, mse_gibbs_lap_2_std = np.mean(np.sqrt(np.stack(data[2])), axis=1), np.std(np.sqrt(np.stack(data[2])), axis=1)
mse_iso_mean, mse_iso_std = np.mean(np.sqrt(np.stack(data[3])), axis=1), np.std(np.sqrt(np.stack(data[3])), axis=1)
mse_ep_mean, mse_ep_std = np.mean(np.sqrt(np.stack(data[4])), axis=1), np.std(np.sqrt(np.stack(data[4])), axis=1)

mae_gibbs_mean, mae_gibbs_std = np.mean(np.stack(data[5]), axis=1), np.std(np.stack(data[5]), axis=1)
mae_gibbs_lap_1_mean, mae_gibbs_lap_1_std = np.mean(np.stack(data[6]), axis=1), np.std(np.stack(data[6]), axis=1)
mae_gibbs_lap_2_mean, mae_gibbs_lap_2_std = np.mean(np.stack(data[7]), axis=1), np.std(np.stack(data[7]), axis=1)
mae_iso_mean, mae_iso_std = np.mean(np.stack(data[8]), axis=1), np.std(np.stack(data[8]), axis=1)
mae_ep_mean, mae_ep_std = np.mean(np.stack(data[9]), axis=1), np.std(np.stack(data[9]), axis=1)

In [41]:
mse_gibbs_mean, mse_gibbs_std, mae_gibbs_mean, mae_gibbs_std

(array([0.75486152, 0.45529283, 0.42548402]),
 array([0.40562141, 0.19208781, 0.15249287]),
 array([0.65142905, 0.37918811, 0.35712677]),
 array([0.36936014, 0.1845413 , 0.15140595]))

In [42]:
mse_gibbs_lap_1_mean, mse_gibbs_lap_1_std, mae_gibbs_lap_1_mean, mae_gibbs_lap_1_std

(array([1.85179285, 0.76749957, 0.50390935]),
 array([1.66120229, 0.51619153, 0.21120904]),
 array([1.60258888, 0.65523407, 0.43030204]),
 array([1.43863866, 0.46074647, 0.20277251]))

In [43]:
mse_gibbs_lap_2_mean, mse_gibbs_lap_2_std, mae_gibbs_lap_2_mean, mae_gibbs_lap_2_std

(array([5.0493709 , 1.58732659, 0.7584477 ]),
 array([4.45426507, 1.38456222, 0.48601033]),
 array([4.37962748, 1.36658267, 0.65920047]),
 array([3.86169132, 1.20520346, 0.44460449]))

In [44]:
mse_iso_mean, mse_iso_std, mae_iso_mean, mae_iso_std

(array([17.6136879 ,  5.94999882,  2.06949857]),
 array([0.71969864, 0.32629915, 0.27967789]),
 array([15.28232846,  5.16397725,  1.80131601]),
 array([0.65856631, 0.32457826, 0.28976427]))

In [46]:
mse_ep_mean, mse_ep_std, mae_ep_mean, mae_ep_std

(array([6.43775976, 3.75967246, 1.80136446]),
 array([0.28750483, 0.25511229, 0.27125207]),
 array([5.59796205, 3.27380098, 1.57094167]),
 array([0.31167939, 0.26638965, 0.28317918]))

# Nasa 3

In [48]:
with open("experiment_results/nasa3_100_2025-01-27-12-49-50.json", 'r') as f:
    data = json.load(f)

mse_gibbs_mean, mse_gibbs_std = np.mean(np.sqrt(np.stack(data[0])), axis=1), np.std(np.sqrt(np.stack(data[0])), axis=1)
mse_gibbs_lap_1_mean, mse_gibbs_lap_1_std = np.mean(np.sqrt(np.stack(data[1])), axis=1), np.std(np.sqrt(np.stack(data[1])), axis=1)
mse_gibbs_lap_2_mean, mse_gibbs_lap_2_std = np.mean(np.sqrt(np.stack(data[2])), axis=1), np.std(np.sqrt(np.stack(data[2])), axis=1)
mse_iso_mean, mse_iso_std = np.mean(np.sqrt(np.stack(data[3])), axis=1), np.std(np.sqrt(np.stack(data[3])), axis=1)
mse_ep_mean, mse_ep_std = np.mean(np.sqrt(np.stack(data[4])), axis=1), np.std(np.sqrt(np.stack(data[4])), axis=1)

mae_gibbs_mean, mae_gibbs_std = np.mean(np.stack(data[5]), axis=1), np.std(np.stack(data[5]), axis=1)
mae_gibbs_lap_1_mean, mae_gibbs_lap_1_std = np.mean(np.stack(data[6]), axis=1), np.std(np.stack(data[6]), axis=1)
mae_gibbs_lap_2_mean, mae_gibbs_lap_2_std = np.mean(np.stack(data[7]), axis=1), np.std(np.stack(data[7]), axis=1)
mae_iso_mean, mae_iso_std = np.mean(np.stack(data[8]), axis=1), np.std(np.stack(data[8]), axis=1)
mae_ep_mean, mae_ep_std = np.mean(np.stack(data[9]), axis=1), np.std(np.stack(data[9]), axis=1)

In [49]:
mse_gibbs_mean, mse_gibbs_std, mae_gibbs_mean, mae_gibbs_std

(array([0.77775296, 0.51407111, 0.42776798]),
 array([0.38424476, 0.22462073, 0.14168812]),
 array([0.66404803, 0.43404554, 0.3605003 ]),
 array([0.34290112, 0.21127255, 0.13781394]))

In [50]:
mse_gibbs_lap_1_mean, mse_gibbs_lap_1_std, mae_gibbs_lap_1_mean, mae_gibbs_lap_1_std

(array([1.87718098, 0.78732665, 0.50279748]),
 array([1.81899236, 0.53642918, 0.19750653]),
 array([1.61738468, 0.67423215, 0.4294521 ]),
 array([1.58001574, 0.4767227 , 0.18967366]))

In [51]:
mse_gibbs_lap_2_mean, mse_gibbs_lap_2_std, mae_gibbs_lap_2_mean, mae_gibbs_lap_2_std

(array([5.29896666, 1.6693721 , 0.73239572]),
 array([4.59019287, 1.4366335 , 0.45123969]),
 array([4.59790431, 1.43662455, 0.63178844]),
 array([3.98640893, 1.25551252, 0.40779674]))

In [52]:
mse_iso_mean, mse_iso_std, mae_iso_mean, mae_iso_std

(array([17.64310221,  6.03529948,  2.09313747]),
 array([0.81016934, 0.38692261, 0.28799018]),
 array([15.297072  ,  5.24185043,  1.81492374]),
 array([0.72079059, 0.3818246 , 0.30144826]))

In [53]:
mse_ep_mean, mse_ep_std, mae_ep_mean, mae_ep_std

(array([7.22549302, 2.79134091, 1.96028276]),
 array([0.26602827, 0.27184573, 0.27344539]),
 array([6.28625405, 2.42518909, 1.71320367]),
 array([0.27929335, 0.2837262 , 0.28596958]))